version: "3"
services:
  entryapp:
    build: ./data_entry
    networks:
      - entry-mysql
      - auth-entry
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    healthcheck:
       test: curl -f http://localhost:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/weatherdb?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "create-drop",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.datasource.driverClassName" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.show-sql" : "true",
        "server.port" : "8080"
      }'
    expose:
      - "3306"
      - "8080"
      - "4444"
    container_name: data_entry_app

  mysqldb:
    image: mysql:latest
    networks:
      - entry-mysql
      - analy-mysql
      - show-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
      - "8080"
      - "5000"
      - "3005"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3306"]
        interval: 3s
        timeout: 10s
        retries: 30
    container_name: mysqldb
  
  authenticationservice:
    build: ./authentication_service
    networks:
      - auth-entry
      - show-auth
    ports:
      - "4444:4444"
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port" : "4444"
      }'
    expose:
      - "8080"
      - "4444"
      - "3005"
    container_name: authenticationservice

  analyticsservice:
    build: ./analytics_service
    networks:
      - analy-mysql
    ports:
      - "5000:5000"
    depends_on:
      entryapp:
        condition: service_started
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/weatherdb?",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "create-drop",
        "server.port" : "5000"
      }'
    expose:
      - "5000"
      - "3306"
    container_name: analyticsservice

  show_results:
    build: ./show_results
    networks:
      - show-mysql
      - show-auth
    ports:
      - "3005:3005"
    depends_on:
      analyticsservice:
        condition: service_started
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/weatherdb?",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "create-drop",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.datasource.driverClassName" : "com.mysql.cj.jdbc.Driver",
        "server.port" : "3005"
      }'
    expose:
      - "3306"
      - "3005"
      - "4444"
    container_name: show_results

networks:
  entry-mysql:
  auth-entry:
  analy-mysql:
  show-auth:
  show-mysql: